module Imported where

import DatabaseTypes

lenders = [ Lender {lenderId = LenderId {lenderIdLogin = "martijn"}, lenderFirstName = "Martijn", lenderLastName = "Schrage", lenderGender = M, lenderMail = "martijn@oblomov.com", lenderStreet = "Kerkstraat", lenderStreetNr = "15", lenderCity = "Utrecht", lenderZipCode = "3581 RA", lenderCoord = (0.0,0.0), lenderImage = "lender_1.jpg", lenderRating = 5, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Henny"}, lenderFirstName = "Henny", lenderLastName = "Verweij", lenderGender = M, lenderMail = "Henny@gmail.com", lenderStreet = "Franz Schubertstraat", lenderStreetNr = "39", lenderCity = "Utrecht", lenderZipCode = "3533 GT", lenderCoord = (0.0,0.0), lenderImage = "lender_2.jpg", lenderRating = 5, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Jaap"}, lenderFirstName = "Jaap", lenderLastName = "Lageman", lenderGender = M, lenderMail = "jaap@bpcutrecht.nl", lenderStreet = "Kerkstraat", lenderStreetNr = "17", lenderCity = "Utrecht", lenderZipCode = "3581 RA", lenderCoord = (0.0,0.0), lenderImage = "lender_3.jpg", lenderRating = 5, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Hans"}, lenderFirstName = "Hans", lenderLastName = "Pietersen", lenderGender = M, lenderMail = "Hans@Gmail.com", lenderStreet = "traay", lenderStreetNr = "18", lenderCity = "Driebergen", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_4.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Frans"}, lenderFirstName = "Frans", lenderLastName = "Verbeek", lenderGender = M, lenderMail = "Frans@Gmail.com", lenderStreet = "slotlaan", lenderStreetNr = "19", lenderCity = "Zeist", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_5.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Frits"}, lenderFirstName = "Frits", lenderLastName = "Spits", lenderGender = M, lenderMail = "Frits@gmail.com", lenderStreet = "", lenderStreetNr = "20", lenderCity = "Zeist", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_6.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Piet"}, lenderFirstName = "Piet", lenderLastName = "Paaltjes", lenderGender = M, lenderMail = "Piet@gmail.com", lenderStreet = "", lenderStreetNr = "21", lenderCity = "Zeist", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_7.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Xander"}, lenderFirstName = "Xander", lenderLastName = "de Bouvier", lenderGender = M, lenderMail = "Xander@gmail.com", lenderStreet = "", lenderStreetNr = "22", lenderCity = "Zeist", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_8.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Truus"}, lenderFirstName = "Truus", lenderLastName = "Hanekam", lenderGender = F, lenderMail = "Truus@gmail.com", lenderStreet = "", lenderStreetNr = "23", lenderCity = "Amsterdam", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_9.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Anita"}, lenderFirstName = "Anita", lenderLastName = "Burgemeester", lenderGender = F, lenderMail = "Anita@gmail.com", lenderStreet = "", lenderStreetNr = "24", lenderCity = "Amsterdam", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_10.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Hanneke"}, lenderFirstName = "Hanneke", lenderLastName = "Rock", lenderGender = F, lenderMail = "Hanneke@gmail.com", lenderStreet = "", lenderStreetNr = "25", lenderCity = "Amsterdam", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_11.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Irene"}, lenderFirstName = "Irene", lenderLastName = "Rood", lenderGender = F, lenderMail = "Irene@gmail.com", lenderStreet = "", lenderStreetNr = "26", lenderCity = "Amsterdam", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_12.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Carla"}, lenderFirstName = "Carla", lenderLastName = "Baars", lenderGender = F, lenderMail = "Carla@gmail.com", lenderStreet = "", lenderStreetNr = "27", lenderCity = "Hilversum", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_13.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Karin"}, lenderFirstName = "Karin", lenderLastName = "Snoek", lenderGender = F, lenderMail = "Karin@gmail.com", lenderStreet = "", lenderStreetNr = "28", lenderCity = "Hilversum", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_14.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Jessie"}, lenderFirstName = "Jessie", lenderLastName = "Smid", lenderGender = F, lenderMail = "Jessie@gmail.com", lenderStreet = "", lenderStreetNr = "29", lenderCity = "Hilversum", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_15.jpg", lenderRating = 0, lenderItems = []}
         , Lender {lenderId = LenderId {lenderIdLogin = "Matt"}, lenderFirstName = "Matt", lenderLastName = "Jansen", lenderGender = M, lenderMail = "Matt@gmail.com", lenderStreet = "kennedylaan", lenderStreetNr = "17", lenderCity = "Utrecht", lenderZipCode = "", lenderCoord = (0.0,0.0), lenderImage = "lender_16.jpg", lenderRating = 0, lenderItems = []}
         ]
items = [ Item {itemId = ItemId (-1), itemOwner = LenderId {lenderIdLogin = "martijn"}, itemPrice = 0, itemName = "Abbey Road", itemDescr = "Come Together\nSomething\nMaxwell's Silver Hammer\nOh! Darling\nOctopus's Garden\nI Want You (she's So Heavy)\nHere Comes The Sun\nBecause\nYou Never Give Me Your Money\nSun King\nMean Mr. Mustard\nPolythene Pam\nShe Came In Through The Bathroom Window\nGolden Slumbers\nCarry That Weight\nThe End\nHer Majesty", itemState = "Prima", itemImage = "cd_1.jpg", itemCategory = CD {cdArtist = "The Beatles", cdYear = 1969, cdGenre = "Pop/Rock"}, itemBorrowed = Nothing}
        , Item {itemId = ItemId (-1), itemOwner = LenderId {lenderIdLogin = "Henny"}, itemPrice = 0, itemName = "Mahler Symphonies", itemDescr = "Disk 1\n1. New York Philharmonic - I. Langsam. Schleppend. Wie Ein Naturlaut. Im Anfang Sehr Gem\65533chlich - \n2. Ii. Kr\65533ftig Bewegt, Doch Nicht Zu Schnell - 2008 Remastered\n3. Iii. Feierlich Und Gemessen, Ohne Zu Schleppen - 2008 Remastered\n4. Iv. St\65533rmisch Bewegt - Energisch - 2008 Remastered\nDisk 2\n1. New York Philharmonic - Symphony No. 2 In C Minor 'resurrection': I. Allegro Maestoso - 2008 R\nDisk 3\n1. New York Philharmonic / Collegiate Chorale - Ii. Andante Moderato - 2008 Remastered\n2. Iii. In Ruhig Fliessender Bewegung - 2008 Remastered\n3. Iv. 'urlicht'. Sehr Feierlich, Aber Schlicht - 2008 Remastered\n4. V. Im Tempo Des Scherzos. Wild Herausfahrend - 2008 Remastered\nDisk 4\n1. New York Philharmonic - Symphony No. 3 In D Minor: I. Kr\65533ftig - 2008 Remastered\nDisk 5\n1. New York Philharmonic / Women's Chorus of the Schola Cantorum / Boys' - Ii. Tempo Di Menuetto - 2002. Iii. Comodo. Scherzando - 2008 Remastered\n3. Iv. Sehr Langsam\n4. V. Lustig Im Tempo Und Keck Im Ausdruck - 2008 Remastered\n5. Vi. Langsam - 2008 Remastered", itemState = "", itemImage = "cd_2.jpg", itemCategory = CD {cdArtist = "Mahler", cdYear = 2008, cdGenre = "Klassiek"}, itemBorrowed = Nothing}
        , Item {itemId = ItemId (-1), itemOwner = LenderId {lenderIdLogin = "Matt"}, itemPrice = 0, itemName = "John Cage", itemDescr = "", itemState = "", itemImage = "cd_3.jpg", itemCategory = CD {cdArtist = "John Cage", cdYear = 0, cdGenre = ""}, itemBorrowed = Nothing}
        , Item {itemId = ItemId (-1), itemOwner = LenderId {lenderIdLogin = "Hans"}, itemPrice = 0, itemName = "Guitar Transcriptions", itemDescr = "1. Bach: Partita for Flute solo in A minor, BWV 1013\n2. Bach: Well-Tempered Clavier, Book 1: Prelude and Fugue no 9 in E major, BWV 854\n3. Bach: Capriccio in B flat major on the departure of his Most Beloved Brother, BWV 992\n4. Bach: Concerto in D minor after Alessandro Marcello, BWV 974 \n5. Bach: Sonata for Violin solo no 1 in G minor, BWV 1001 \n6. 5 Little Preludes, Bwv 939-943: Prelude In C Major, Bwv 939 \n7. Capriccio Sopra La Lontananza De Il Fratro Dilettissimo In B Flat Majo \n8. Keyboard Concerto In D Minor, Bwv 974 (After A. Marcello's Oboe Concert\n9. Keyboard Concerto In D Minor, Bwv 974 (After A. Marcello's Oboe Concert\n10. Keyboard Concerto In D Minor, Bwv 974 (After A. Marcello's Oboe Concert\n11. Violin Sonata No. 1 In G Minor, Bwv 1001 (Arr. E. Voorhorst for Guitar)\n12. Violin Sonata No. 1 In G Minor, Bwv 1001 (Arr. E. Voorhorst for Guitar)\n13. Violin Sonata No. 1 In G Minor, Bwv 1001 (Arr. E. Voorhorst for Guitar)\n14. Violin Sonata No. 1 In G Minor, Bwv 1001 (Arr. E. Voorhorst for Guitar", itemState = "", itemImage = "cd_4.jpg", itemCategory = CD {cdArtist = "Bach", cdYear = 2005, cdGenre = "Klassiek"}, itemBorrowed = Nothing}
        , Item {itemId = ItemId (-1), itemOwner = LenderId {lenderIdLogin = "Frans"}, itemPrice = 0, itemName = "Violin Concertos BWV 1041/1042/1043/1060l", itemDescr = "1. Bach: Concerto for Violin no 1 in A minor, BWV 1041 \r2. Bach: Concerto for Violin no 2 in E major, BWV 1042 \r3. Bach: Concerto for 2 Violins in D minor, BWV 1043 \r4. Bach: Concerto for Oboe and Violin in C minor, BWV 1060", itemState = "", itemImage = "cd_5.jpg", itemCategory = CD {cdArtist = "Bach", cdYear = 2004, cdGenre = "Klassiek"}, itemBorrowed = Nothing}
        , Item {itemId = ItemId (-1), itemOwner = LenderId {lenderIdLogin = "Frits"}, itemPrice = 0, itemName = "Slash", itemDescr = "1. Apocalyptic Love\n2. One Last Thrill\n3. Standing In the Sun\n4. You're A Lie\n5. No More Heroes\n6. Halo\n7. We Will Roam\n8. Anastasia\n9. Not for Me\n10. Bad Rain\n 11. Hard & Fast\n12. Far and Away\n 13. Shots Fired\n14. Carolina (Bonustrack)\n15. Crazy Life (Bonustrack)\nDisk 2  1. Apocalyptic Love Documentary ", itemState = "", itemImage = "cd_6.jpg", itemCategory = CD {cdArtist = "Slash", cdYear = 2012, cdGenre = "Heavy Metal"}, itemBorrowed = Nothing}
        , Item {itemId = ItemId (-1), itemOwner = LenderId {lenderIdLogin = "Piet"}, itemPrice = 0, itemName = "Eye in the sky", itemDescr = "1. Sirius (1:57)\n2. Eye In The Sky (4:35)\n3. Children Of The Moon (4:49)\n4. Gemini (2:09)\n5. Silence And I (7:17)\n6. You're Gonna Get Your Fingers Burned (4:19)\n7. Psychobabble (4:50)\n8. Mammagamma - Instrumental (3:34)\n9. Step By Step (3:52)\n10. Old And Wise (4:57)\n11. Sirius - Demo (1:53)\n12. Old & Wise - Eric Woolfson Guide Vocal (4:31)\n13. Any Other Day - Studio Demo (1:40\n\r14. Silence & I - Early Version; Eric Woolfson Guide Vocal (7:33)\n15. The Naked Eye (10:47)\n16. Eye Pieces - Classical Naked Eye (7:51) ", itemState = "", itemImage = "cd_7.jpg", itemCategory = CD {cdArtist = "Alan Parsons Project", cdYear = 1980, cdGenre = "Pop/Rock"}, itemBorrowed = Nothing}
        , Item {itemId = ItemId (-1), itemOwner = LenderId {lenderIdLogin = "Xander"}, itemPrice = 0, itemName = "Dark Side of the Moon", itemDescr = "1. Speak To Me (2011 - Remaster)\n2. Breathe (In the Air) [2011 - Remaster]\n3. On the Run (2011 - Remaster)\n4. Time (2011 - Remaster)\n5. The Great Gig In the Sky (2011 - Remaster)\n6. Money (2011 - Remaster)\n7. Us and Them (2011 - Remaster)\n8. Any Colour You Like (2011 - Remaster)\n9. Brain Damage (2011 - Remaster)\n10. Eclipse (2011 - Remaster)", itemState = "", itemImage = "cd_8.jpg", itemCategory = CD {cdArtist = "Pink Floyd", cdYear = 1973, cdGenre = "Pop/Rock"}, itemBorrowed = Nothing}
        , Item {itemId = ItemId (-1), itemOwner = LenderId {lenderIdLogin = "Truus"}, itemPrice = 0, itemName = "The Koln Concert", itemDescr = "1. Part I\n2. Part IIa\n3. Part IIb\n4. Part IIc ", itemState = "", itemImage = "cd_9.jpg", itemCategory = CD {cdArtist = "Keith Jarret", cdYear = 1994, cdGenre = "Jazz"}, itemBorrowed = Nothing}
        , Item {itemId = ItemId (-1), itemOwner = LenderId {lenderIdLogin = "Anita"}, itemPrice = 0, itemName = "Khmer", itemDescr = "1. Khmer\n2. Tlon\n3. Access / Song Of Sand I\n4. On Stream\n5. Platonic Years\n6. Phum\n7. Song Of Sand Ii\n8. Exit", itemState = "", itemImage = "cd_10.jpg", itemCategory = CD {cdArtist = "Nils Petter Molvaer", cdYear = 2005, cdGenre = "Jazz"}, itemBorrowed = Nothing}
        ]